spring:
  messages:
    basename: 'message/messages'
    encoding: 'UTF-8'
    
  redis:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
    port: 16377
    host: 127.0.0.1

logging:
  level:
    todo : 'DEBUG'
  path: '/app/payment-api/logs/'
  
payment-secretkey: 'kakaopaygogogo!!'