
server:
  port: 8081

spring:
  http:
    encoding:
      charset: 'UTF-8'
      enabled: true
      force: true
  messages:
    basename: 'message/messages'
    encoding: 'UTF-8'
    
  redis:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
    port: 16377
    host: 127.0.0.1
    
logging:
  level:
    com.payment: DEBUG
    org.springframework.web: ERROR
    com.howtodoinjava: DEBUG
    org.hibernate: ERROR
  file:
    path: '/app/payment-api/logs/'
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"

payment-secretkey: 'kakaopaygogogo!!'
