spring:
  messages:
    basename: message/messages
    encoding: UTF-8

  redis:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
  port: 16379
  host: localhost

logging:
  level:
    todo : DEBUG
  path: /app/payment-api/logs/